# coding: utf-8

# flake8: noqa

"""
    Simple API

    A minimal API for testing

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from test_service_client.api.default_api import DefaultApi

# import ApiClient
from test_service_client.api_response import ApiResponse
from test_service_client.api_client import ApiClient
from test_service_client.configuration import Configuration
from test_service_client.exceptions import OpenApiException
from test_service_client.exceptions import ApiTypeError
from test_service_client.exceptions import ApiValueError
from test_service_client.exceptions import ApiKeyError
from test_service_client.exceptions import ApiAttributeError
from test_service_client.exceptions import ApiException

# import models into sdk package
from test_service_client.models.item import Item
