# coding: utf-8

# flake8: noqa
"""
    Simple API

    A minimal API for testing

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from test_service_client.models.item import Item
