# coding: utf-8

"""
    Simple API

    A minimal API for testing

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from test_service_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_get_items(self) -> None:
        """Test case for get_items

        Get all items
        """
        pass


if __name__ == '__main__':
    unittest.main()
