"""
lynnx-blog-mcp-server - Test Fixtures

Test data and fixtures for consistent testing.
Provides sample data, mock responses, and test utilities.

Generated by mcp-cli tool.
"""

from typing import Dict, Any, List

# Sample API responses
SAMPLE_SUCCESS_RESPONSE = {
    "status": "success",
    "message": "Operation completed successfully",
    "data": {
        "id": 123,
        "name": "Test Resource",
        "created_at": "2024-01-01T00:00:00Z",
        "updated_at": "2024-01-01T12:00:00Z"
    }
}

SAMPLE_ERROR_RESPONSE = {
    "status": "error",
    "message": "Operation failed",
    "error": {
        "code": "INVALID_REQUEST",
        "details": "Missing required parameter: id"
    }
}

SAMPLE_LIST_RESPONSE = {
    "status": "success",
    "data": [
        {"id": 1, "name": "Item 1", "active": True},
        {"id": 2, "name": "Item 2", "active": False},
        {"id": 3, "name": "Item 3", "active": True}
    ],
    "pagination": {
        "total": 3,
        "page": 1,
        "per_page": 10,
        "has_next": False
    }
}

# MCP tool test data
SAMPLE_TOOL_ARGUMENTS = {
    "hello_world": {
        "valid": {"name": "Alice"},
        "invalid": {"invalid_param": "value"}
    }
}

SAMPLE_TOOL_RESPONSES = {
    "hello_world": "Hello, Alice! This is lynnx-blog-mcp-server."
}

# Configuration test data
VALID_CONFIG_DATA = {
    "api_base_url": "https://api.example.com",
    "api_key": "test-key-123",
    "timeout": 30,
    "max_retries": 3
}

INVALID_CONFIG_DATA = {
    "api_base_url": "invalid-url",
    "timeout": -1
} 